import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

let SUPABASE_URL=window.SUPABASE_URL||"", SUPABASE_PUBLISHABLE_KEY=window.SUPABASE_PUBLISHABLE_KEY||"";
const app=document.querySelector('#app'); let sb=null,user=null,room=null,channel=null,timer=null,poll=null,autoNext=null;
const nameKey='onomatope_player_name';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stars=n=>'★'.repeat(n)+'☆'.repeat(3-n);
function render(x){app.innerHTML=x} function fail(e){console.error(e);document.querySelectorAll('.error').forEach(x=>x.remove());app.insertAdjacentHTML('afterbegin',`<div class="error">${esc(e.message||e)}</div>`)}
async function config(){if(!SUPABASE_URL||SUPABASE_URL.includes('YOUR_')||!SUPABASE_PUBLISHABLE_KEY||SUPABASE_PUBLISHABLE_KEY.includes('YOUR_'))throw Error('config.js に Supabase の URL と Publishable Key を設定してください。')}
async function auth(){if(!sb)throw Error('サーバー設定が未完了です');const {data,error}=await sb.auth.signInAnonymously();if(error)throw error;user=data.user}
function savedName(){return localStorage.getItem(nameKey)||''} function setName(n){localStorage.setItem(nameKey,n)}
function home(){
 render(`<div class="wrap"><div class="hero"><div class="tag">ONLINE PARTY GAME / MAX 4</div><h1>オノマトペ<br><span class="orange">早押し対戦</span></h1><p class="sub">2つの音から状況を想像。<br>誰より早く答えろ！</p></div><div class="panel homePanel"><h2>今すぐ遊ぶ</h2><input id="name" maxlength="12" value="${esc(savedName())}" placeholder="プレイヤー名"><div class="twoBtns"><button id="create">ルームを作る</button><button class="dark" id="join">ルームに参加</button></div><button class="yellow full" id="questions">問題を作る</button><p class="note">最大4人 / 10問 / 1問10秒 / 正解+100pt。回答後は👍👎で評価できます。</p></div></div>`);
 document.querySelector('#create').onclick=()=>enter(true);document.querySelector('#join').onclick=()=>joinUI();document.querySelector('#questions').onclick=questionsUI;
}
async function enter(create){try{await auth();const n=(document.querySelector('#name').value.trim()||'プレイヤー').slice(0,12);setName(n);if(!create)return joinUI();for(let i=0;i<5;i++){const code=Math.random().toString(36).slice(2,6).toUpperCase();const {data,error}=await sb.rpc('create_room',{p_code:code,p_name:n});if(!error)return connect(data.room_id,n)}throw Error('ルーム作成に失敗しました。もう一度お試しください。')}catch(e){fail(e)}}
function joinUI(){const preset=new URLSearchParams(location.search).get('room')||'';render(`<div class="wrap"><div class="hero"><div class="tag">JOIN ROOM</div><h1>ルームに<br><span class="orange">参加</span></h1></div><div class="panel"><input id="name" maxlength="12" value="${esc(savedName())}" placeholder="プレイヤー名"><input id="code" maxlength="4" value="${esc(preset.toUpperCase())}" placeholder="4文字コード" style="text-transform:uppercase"><button id="go" class="full">参加する</button><button class="dark full" id="back">戻る</button></div></div>`);document.querySelector('#back').onclick=home;document.querySelector('#go').onclick=async()=>{try{await auth();const n=(document.querySelector('#name').value.trim()||'プレイヤー').slice(0,12),c=document.querySelector('#code').value.trim().toUpperCase();setName(n);const {data,error}=await sb.rpc('join_room',{p_code:c,p_name:n});if(error)throw error;await connect(data.room_id,n)}catch(e){fail(e)}}}
async function connect(roomId,name){room=roomId;channel=sb.channel('room:'+roomId,{config:{private:false,presence:{key:user.id},broadcast:{ack:true}}});channel.on('broadcast',{event:'state'},()=>loadRoom()).on('presence',{event:'sync'},()=>loadRoom());await channel.subscribe();await channel.track({user_id:user.id,name});startPoll();await loadRoom()}
function startPoll(){clearInterval(poll);poll=setInterval(()=>loadRoom().catch(()=>{}),1500)}
async function loadRoom(){const {data:r,error}=await sb.from('rooms').select('*').eq('id',room).single();if(error)throw error;const {data:p,error:e}=await sb.from('players').select('*').eq('room_id',room).order('joined_at');if(e)throw e;if(r.status==='lobby')lobby(r,p);else if(r.status==='finished')finish(p,r);else game(r,p)}
function broadcast(event,payload={}){channel?.send({type:'broadcast',event:'state',payload:{event,...payload}})}
function shareUrl(code){return `${location.origin}${location.pathname}?room=${encodeURIComponent(code)}`}
async function shareRoom(code){const url=shareUrl(code);try{if(navigator.share)await navigator.share({title:'オノマトペ早押し対戦',text:`ルーム「${code}」に参加しよう！`,url});else{await navigator.clipboard.writeText(url);alert('参加リンクをコピーしました！')}}catch(e){if(e.name!=='AbortError')prompt('このリンクを共有してください',url)}}
function lobby(r,p){const host=r.host_user_id===user.id,allReady=p.length>=2&&p.filter(x=>x.user_id!==r.host_user_id).every(x=>x.ready);render(`<div class="wrap"><div class="hero"><div class="tag">ROOM</div><h1>${esc(r.code)}</h1><p class="sub">このコードを友達に共有！</p></div><div class="panel"><div class="roomcode">${esc(r.code)}</div><div class="twoBtns"><button id="share" class="yellow">🔗 共有</button><button id="qr" class="dark">▣ QRコード</button></div><h3>参加者 ${p.length}/4</h3><div class="players">${p.map(x=>`<div class="player ${x.user_id===user.id?'me':''}"><b>${esc(x.name)}</b><div class="score">${x.score} pt</div><div class="status">${x.user_id===r.host_user_id?'HOST':(x.ready?'✓ READY':'未準備')}</div></div>`).join('')}</div><div class="readyBox">${!host?`<button id="ready" class="${p.find(x=>x.user_id===user.id)?.ready?'dark':'yellow'}">${p.find(x=>x.user_id===user.id)?.ready?'準備OK ✓':'READYする'}</button>`:`<div class="note">${allReady?'全員準備OK！ゲームを開始できます。':'参加者全員のREADYを待っています。'}</div>`}</div>${host?`<button id="start" ${allReady?'':'disabled'}>ゲーム開始</button>`:`<p class="note center">全員がREADYになったらホストがゲームを開始します。</p>`}<button class="dark full" id="homeBtn">退出</button></div></div>`);document.querySelector('#share').onclick=()=>shareRoom(r.code);document.querySelector('#qr').onclick=()=>qrModal(r.code);document.querySelector('#ready')?.addEventListener('click',async()=>{const me=p.find(x=>x.user_id===user.id);const {error}=await sb.rpc('set_ready',{p_room_id:room,p_ready:!me.ready});if(error)fail(error);else broadcast('ready')});document.querySelector('#start')?.addEventListener('click',async()=>{const {error}=await sb.rpc('start_game',{p_room_id:room});if(error)fail(error);else broadcast('start')});document.querySelector('#homeBtn').onclick=leaveRoom}
function qrModal(code){const url=shareUrl(code);document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalCard"><button class="close" id="close">×</button><h2>参加用QRコード</h2><div id="qrcode"></div><b>${esc(code)}</b><p class="note">スマホのカメラで読み取って参加できます。</p></div></div>`);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js';s.onload=()=>new QRCode(document.querySelector('#qrcode'),{text:url,width:220,height:220});document.head.appendChild(s);document.querySelector('#close').onclick=()=>document.querySelector('#modal')?.remove()}
async function leaveRoom(){clearInterval(poll);clearInterval(timer);clearTimeout(autoNext);try{await sb.rpc('leave_room',{p_room_id:room})}catch(e){console.warn(e)};if(channel)try{await channel.unsubscribe()}catch{};location.href=location.pathname}
async function getQuestion(){const {data,error}=await sb.rpc('get_current_question',{p_room_id:room});if(error)throw error;return data}
async function getAnswer(r){const {data,error}=await sb.rpc('get_round_result',{p_room_id:room,p_question_no:r.question_no});if(error)throw error;return data?.[0]||null}
async function reactions(aid){const {data,error}=await sb.from('answer_reactions').select('reaction,user_id').eq('answer_id',aid);if(error)throw error;return data||[]}
async function game(r,p){clearInterval(timer);clearTimeout(autoNext);const q=await getQuestion();const rem=Math.max(0,Math.ceil((new Date(r.question_deadline||0).getTime()-Date.now())/1000));const answer=r.phase==='result'?await getAnswer(r):null;const rx=answer?await reactions(answer.id):[];const good=rx.filter(x=>x.reaction==='good').length,bad=rx.filter(x=>x.reaction==='bad').length,my=rx.find(x=>x.user_id===user.id)?.reaction;const host=r.host_user_id===user.id;if(r.phase==='result')return resultPhase(r,p,q,answer,good,bad,my,host);render(`<div class="wrap"><div class="panel"><div class="qhead"><b>オノマトペ早押し</b><span>${r.question_no+1} / 10</span></div><div class="players">${p.map(x=>`<div class="player ${x.user_id===user.id?'me':''}"><b>${esc(x.name)}</b><div class="score">${x.score} pt</div><div class="status">${x.buzzed_at?'⚡ 回答権':'待機'}</div></div>`).join('')}</div></div><div class="panel"><div id="timer" class="timer ${rem<=3?'danger':''}">${rem}</div><div class="words"><div class="word">${esc(q.word1)}</div><div class="word">${esc(q.word2)}</div></div><div class="difficulty">難易度 ${stars(q.difficulty)}</div><button id="buzz" class="buzz" ${r.buzzed_by||rem<=0?'disabled':''}>🔥 早押し！</button><div id="answer" class="answer ${r.buzzed_by===user.id?'show':''}">${r.buzzed_by===user.id?`<div class="winner">⚡ 回答権GET！</div><input id="ans" maxlength="120" placeholder="状況を入力"><button id="submit">回答する</button>`:''}</div></div><div class="panel"><h3>ルール</h3><p class="note">最初に押した1人だけが回答。正解+100pt、不正解0pt。時間切れは0pt。回答後に全員で👍👎評価。</p></div></div>`);timer=setInterval(async()=>{const n=Math.max(0,Math.ceil((new Date(r.question_deadline).getTime()-Date.now())/1000));const el=document.querySelector('#timer');if(el){el.textContent=n;el.className='timer '+(n<=3?'danger':'')}if(n<=0){clearInterval(timer);if(host){const {error}=await sb.rpc('timeout_round',{p_room_id:room});if(!error)broadcast('timeout')}}},250);document.querySelector('#buzz')?.addEventListener('click',async()=>{const {data,error}=await sb.rpc('claim_buzz',{p_room_id:room,p_user_id:user.id});if(error)fail(error);else if(data?.claimed){broadcast('buzz',{user_id:user.id});loadRoom().catch(fail)}else alert('先に別のプレイヤーが押しました！')});document.querySelector('#submit')?.addEventListener('click',async()=>{const a=document.querySelector('#ans').value.trim();if(!a)return;const {data,error}=await sb.rpc('submit_answer',{p_room_id:room,p_user_id:user.id,p_answer:a});if(error)fail(error);else broadcast('answer',data)})}
function resultPhase(r,p,q,answer,good,bad,my,host){render(`<div class="wrap"><div class="panel"><div class="qhead"><b>ROUND RESULT</b><span>${r.question_no+1} / 10</span></div><div class="words"><div class="word">${esc(q.word1)}</div><div class="word">${esc(q.word2)}</div></div><div class="resultBox"><div class="resultLabel">${answer?'回答':'時間切れ'}</div>${answer?`<div class="givenAnswer">「${esc(answer.answer)}」</div><div class="official">正解：${esc(answer.official_answer||'')||esc(q.answer||'')}</div><div class="resultPoint ${answer.correct?'correct':'wrong'}">${answer.correct?'🎉 正解！ +100pt':'😵 不正解 0pt'}</div>`:`<div class="givenAnswer">誰も回答しませんでした</div><div class="official">正解を確認！</div>`}</div><div class="reactionArea"><div class="reactionTitle">この回答、どうだった？</div><div class="reactionButtons"><button class="reaction good ${my==='good'?'selected':''}" data-reaction="good">👍 <b>グッド</b><span>${good}</span></button><button class="reaction bad ${my==='bad'?'selected':''}" data-reaction="bad">👎 <b>バッド</b><span>${bad}</span></button></div></div><p class="note">1人1票。押し直しもできます。</p></div><div class="panel"><div class="players">${p.map(x=>`<div class="player ${x.user_id===user.id?'me':''}"><b>${esc(x.name)}</b><div class="score">${x.score} pt</div></div>`).join('')}</div>${host?`<button id="next" class="yellow">次の問題へ</button>`:`<p class="note center">次の問題まで少々お待ちください。</p>`}</div></div>`);document.querySelectorAll('.reaction').forEach(b=>b.onclick=async()=>{if(!answer)return;const {error}=await sb.rpc('react_answer',{p_answer_id:answer.id,p_reaction:b.dataset.reaction});if(error)fail(error);else broadcast('reaction')});document.querySelector('#next')?.addEventListener('click',nextRound);if(host)autoNext=setTimeout(nextRound,5000)}
async function nextRound(){const {error}=await sb.rpc('next_round',{p_room_id:room});if(error)fail(error);else broadcast('next')}
async function handleEvent(e){if(e.event)loadRoom().catch(()=>{})}
async function finish(p,r){clearInterval(timer);clearTimeout(autoNext);p.sort((a,b)=>b.score-a.score);const host=r.host_user_id===user.id;render(`<div class="wrap"><div class="hero"><div class="tag">FINAL RESULT</div><h1>結果発表！</h1></div><div class="panel">${p.map((x,i)=>`<div class="rank"><b>${i+1}位　${esc(x.name)}</b><span>${x.score} pt</span></div>`).join('')}</div><div class="panel" style="text-align:center"><div class="winner">🏆 ${esc(p[0]?.name||'')} の優勝！</div>${host?`<button id="rematch" class="yellow">もう一度遊ぶ</button>`:`<p class="note">ホストが再戦を開始できます。</p>`}<button class="dark full" id="exit">退出</button></div></div>`);document.querySelector('#rematch')?.addEventListener('click',async()=>{const {error}=await sb.rpc('rematch_room',{p_room_id:room});if(error)fail(error);else broadcast('rematch')});document.querySelector('#exit').onclick=leaveRoom}
async function questionsUI(){try{await auth();const {data,error}=await sb.rpc('list_my_questions');if(error)throw error;render(`<div class="wrap"><div class="hero"><div class="tag">QUESTION MAKER</div><h1>問題を<br><span class="orange">作る</span></h1></div><div class="panel"><h2>新しい問題</h2><input id="w1" maxlength="30" placeholder="オノマトペ① 例：ピンポーン"><input id="w2" maxlength="30" placeholder="オノマトペ② 例：ガチャ"><select id="category"><option>日常</option><option>食べ物</option><option>自然</option><option>スポーツ</option><option>学校</option><option>デジタル</option><option>乗り物</option><option>エンタメ</option><option>その他</option></select><input id="answer" maxlength="120" placeholder="正解 例：インターホンが鳴ってドアを開けた"><input id="accepted" maxlength="300" placeholder="許容回答（カンマ区切り）例：インターホン,玄関,ドア"><select id="difficulty"><option value="1">★☆☆ やさしい</option><option value="2" selected>★★☆ ふつう</option><option value="3">★★★ むずかしい</option></select><button id="save" class="full">問題を公開</button><button class="dark full" id="back">戻る</button><p class="note">公開すると対戦問題に採用されます。公開中の問題が10問以上必要です。</p></div><div class="panel"><h2>自分の問題 <small>${data.length}問</small></h2><div class="questionList">${data.map(q=>`<div class="questionItem"><div><b>${esc(q.word1)} ＋ ${esc(q.word2)}</b><div>${esc(q.answer)}</div><small>${esc(q.category)} / ${stars(q.difficulty)} / ${q.is_active?'公開中':'非公開'}</small></div><button class="mini ${q.is_active?'dark':'yellow'}" data-id="${q.id}" data-active="${q.is_active}">${q.is_active?'非公開':'公開'}</button></div>`).join('')}</div></div></div>`);document.querySelector('#back').onclick=home;document.querySelector('#save').onclick=async()=>{const w1=document.querySelector('#w1').value.trim(),w2=document.querySelector('#w2').value.trim(),cat=document.querySelector('#category').value,a=document.querySelector('#answer').value.trim(),acc=document.querySelector('#accepted').value.split(',').map(x=>x.trim()).filter(Boolean),d=Number(document.querySelector('#difficulty').value);if(!w1||!w2||!a){alert('オノマトペ2個と正解を入力してください');return}const {error}=await sb.rpc('create_question',{p_word1:w1,p_word2:w2,p_category:cat,p_answer:a,p_accepted_answers:acc,p_difficulty:d});if(error)fail(error);else questionsUI()};document.querySelectorAll('.mini').forEach(b=>b.onclick=async()=>{const {error}=await sb.rpc('set_question_active',{p_question_id:b.dataset.id,p_active:b.dataset.active!=='true'});if(error)fail(error);else questionsUI()})}catch(e){fail(e)}}
async function init(){try{await config();sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);home()}catch(e){fail(e)}}init();
